version: "3.1"
services:
    webserver:
      image: nginx:alpine
      container_name: factorenergia-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8083:80"

    php-fpm:
      image: bitnami/php-fpm:8.0
      container_name: factorenergia-php-fpm
      working_dir: /application
      volumes:
        - .:/application

    mysql:
      image: mysql:5.7
      container_name: factorenergia-mysql
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/mysql/data:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=toor
        - MYSQL_DATABASE=dbname
        - MYSQL_USER=dbuser
        - MYSQL_PASSWORD=toor
      ports:
        - "8089:3306"
